"use client";

import { Footer } from "@/components/footer";
import Hero from "@/components/hero/Hero";
import Navbar from "@/components/nav/Navbar";
import type { Metadata } from "next";

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName: "Generated by create next app",
  authors: [{ name: "Salman Lartey", url: "https://nextjs.org" }],
  keywords: ["react", "server components"],
  icons: { icon: '/icon.png', },
  twitter: {
    card: "summary_large_image",
  },
  openGraph: {
    url: "https://next-enterprise.vercel.app/",
    images: [
      {
        width: 1200,
        height: 630,
        url: "https://raw.githubusercontent.com/Blazity/next-enterprise/main/project-logo.png",
      },
    ],
  },
};

export default function Home() {
  return (
    <main className="flex flex-col justify-between min-h-screen p-4">
      <Navbar />
      <div>
        {/* Your main content goes here */}
        <Hero />
        {/* ... other content ... */}
        <Footer />
      </div>
    </main>
  );
}
